use std::any::Any;

use kls_stdlib::*;

#[used]
static KEEP: &[&(dyn Any + Send + Sync)] = &[
    &(kls_clock_ms as extern "C" fn() -> f64),
    &(kls_clock_ns as extern "C" fn() -> f64),
    &(kls_clock_s as extern "C" fn() -> f64),
    &(kls_clock_us as extern "C" fn() -> f64),
    &(kls_readd as extern "C" fn() -> f64),
    &(kls_abs as extern "C" fn(f64) -> f64),
    &(kls_acos as extern "C" fn(f64) -> f64),
    &(kls_acosh as extern "C" fn(f64) -> f64),
    &(kls_asin as extern "C" fn(f64) -> f64),
    &(kls_asinh as extern "C" fn(f64) -> f64),
    &(kls_atan as extern "C" fn(f64) -> f64),
    &(kls_atanh as extern "C" fn(f64) -> f64),
    &(kls_cbrt as extern "C" fn(f64) -> f64),
    &(kls_ceil as extern "C" fn(f64) -> f64),
    &(kls_cos as extern "C" fn(f64) -> f64),
    &(kls_cosh as extern "C" fn(f64) -> f64),
    &(kls_eprintd as extern "C" fn(f64) -> f64),
    &(kls_eputchard as extern "C" fn(f64) -> f64),
    &(kls_exp as extern "C" fn(f64) -> f64),
    &(kls_exp2 as extern "C" fn(f64) -> f64),
    &(kls_floor as extern "C" fn(f64) -> f64),
    &(kls_ln as extern "C" fn(f64) -> f64),
    &(kls_log10 as extern "C" fn(f64) -> f64),
    &(kls_log2 as extern "C" fn(f64) -> f64),
    &(kls_printd as extern "C" fn(f64) -> f64),
    &(kls_putchard as extern "C" fn(f64) -> f64),
    &(kls_qrsqrt as extern "C" fn(f64) -> f64),
    &(kls_recip as extern "C" fn(f64) -> f64),
    &(kls_round as extern "C" fn(f64) -> f64),
    &(kls_sin as extern "C" fn(f64) -> f64),
    &(kls_sinh as extern "C" fn(f64) -> f64),
    &(kls_sqrt as extern "C" fn(f64) -> f64),
    &(kls_tan as extern "C" fn(f64) -> f64),
    &(kls_tanh as extern "C" fn(f64) -> f64),
    &(kls_trunc as extern "C" fn(f64) -> f64),
    &(kls_atan2 as extern "C" fn(f64, f64) -> f64),
    &(kls_div_euclid as extern "C" fn(f64, f64) -> f64),
    &(kls_hypot as extern "C" fn(f64, f64) -> f64),
    &(kls_log as extern "C" fn(f64, f64) -> f64),
    &(kls_pow as extern "C" fn(f64, f64) -> f64),
    &(kls_rem_euclid as extern "C" fn(f64, f64) -> f64),
];
